// Generated by CoffeeScript 1.6.3
(function() {
  define(['Quotes'], function(Quotes) {
    var passData;
    passData = function() {
      return JSON.stringify(Quotes.random());
    };
    return {
      showNotification: function() {
        var notification;
        notification = webkitNotifications.createHTMLNotification('notification.html');
        return notification.show();
      }
    };
  });

}).call(this);
