// Generated by CoffeeScript 1.6.3
(function() {
  define(['Quotes'], function(Quotes) {
    var isAvaibleNewAPI;
    isAvaibleNewAPI = webkitNotifications.createHTMLNotification == null;
    return {
      showNotification: function() {
        var cb, data, notification, opt;
        if (isAvaibleNewAPI) {
          data = Quotes.random();
          opt = {
            type: "basic",
            title: "Take a Break!",
            message: data.quote,
            iconUrl: "images/icon-clock-200x200.png",
            items: [
              {
                title: data.author,
                message: data.quote
              }
            ]
          };
          cb = function() {
            return console.log('notification showed');
          };
          return chrome.notifications.create('notifications-id', opt, cb);
        } else {
          notification = webkitNotifications.createHTMLNotification('notification.html');
          return notification.show();
        }
      }
    };
  });

}).call(this);
