// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      R: 'data/Resources',
      Timer: 'core/background/Timer',
      MessageEmitter: 'core/popup/MessageEmitter',
      Player: 'view/Player'
    }
  });

}).call(this);
