// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      R: 'core/data/Resources',
      _: 'core/common/Utils',
      EventEmitter: 'core/common/EventEmitter',
      ConnectionManager: 'view/ConnectionManager',
      TagIO: 'core/persistence/TagIO',
      Timer: 'background/Timer',
      Player: 'view/Player',
      Clock: 'view/Clock',
      Tag: 'view/Tag'
    }
  });

}).call(this);
