// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      R: 'data/Resources',
      Timer: 'core/background/Timer',
      MessageEmitter: 'core/popup/MessageEmitter',
      _: 'common/Utils',
      Player: 'view/Player',
      Clock: 'view/Clock'
    }
  });

}).call(this);
