// Generated by CoffeeScript 1.6.3
(function() {
  require(['config'], function() {
    return require(['ConnectionManager', 'Player'], function(CM, P) {
      return CM.init();
    });
  });

}).call(this);
