// Generated by CoffeeScript 1.6.3
(function() {
  require(['config'], function() {
    return require(['MessageEmitter'], function(MessageEmitter) {
      console.log(MessageEmitter.start);
      return MessageEmitter.start();
    });
  });

}).call(this);
