// Generated by CoffeeScript 1.6.3
(function() {
  require(['config'], function() {
    return require(['Player'], function() {
      return require(['ConnectionManager'], function(CM) {
        return CM.init();
      });
    });
  });

}).call(this);
