// Generated by CoffeeScript 1.6.3
(function() {
  var data;

  data = Quotes.random();

  document.getElementById("quote").innerHTML = data.quote;

  document.getElementById("auth").innerHTML = data.author;

}).call(this);
