// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', 'MessageEmitter'], function(R, MessageEmitter) {
    var T, Timer, changeIcon, counter;
    T = null;
    counter = 0;
    changeIcon = function(n) {
      return chrome.browserAction.setIcon({
        path: R.path.icon + n + ".jpg"
      });
    };
    return Timer = {
      init: function() {
        return chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
          var _name;
          return typeof Timer[_name = request.type] === "function" ? Timer[_name](request) : void 0;
        });
      },
      start: function(req) {
        var n, task, tick;
        if (T != null) {
          return false;
        }
        console.log(R.string.start_timer_msg);
        n = 10;
        tick = req.time / n;
        T = setInterval(function() {
          return task();
        }, tick);
        task = function() {
          if (counter >= 10) {
            Timer.stop();
            return;
          }
          changeIcon(counter);
          return counter++;
        };
        return true;
      },
      pause: function(req) {
        if (T != null) {
          window.clearInterval(T);
          T = null;
          return console.log(R.string.pause_timer_msg);
        }
      },
      stop: function(req) {
        if (T != null) {
          window.clearInterval(T);
          T = null;
        }
        counter = 0;
        changeIcon();
        console.log(R.string.stop_timer_msg);
        return true;
      }
    };
  });

}).call(this);
