// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', 'MessageEmitter'], function(R, MessageEmitter) {
    var T, Timer, changeIcon, iconPath;
    iconPath = 'images/tomato-products-clock-';
    T = null;
    changeIcon = function(n) {
      return chrome.browserAction.setIcon({
        path: iconPath + n + ".jpg"
      });
    };
    return Timer = {
      init: function() {
        return chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
          var _name;
          return typeof Timer[_name = request.type] === "function" ? Timer[_name](request) : void 0;
        });
      },
      start: function(req) {
        var counter, n, task, tick;
        console.log(R.string.start_timer_msg);
        n = 10;
        counter = 0;
        tick = req.time / n;
        T = setInterval(function() {
          return task();
        }, tick);
        task = function() {
          if (counter >= 10) {
            window.clearInterval(T);
            console.log(R.string.stop_timer_msg);
            return;
          }
          changeIcon(counter);
          return counter++;
        };
        return true;
      },
      stop: function(req) {
        if (T != null) {
          window.clearInterval(T);
          return console.log(R.string.stop_timer_msg);
        }
      }
    };
  });

}).call(this);
