// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Utils;
    Utils = (function() {
      function Utils() {}

      Utils.prototype.isDef = function(o) {
        return typeof o !== "undefined";
      };

      return Utils;

    })();
    return new Utils();
  });

}).call(this);
