// Generated by CoffeeScript 1.6.3
(function() {
  define(['R'], function(R) {
    return {
      Tag: (function() {
        function _Class(name, tomatoes) {
          this.name = name;
          this.tomatoes = tomatoes;
        }

        _Class.prototype.toString = function() {
          return JSON.stringify(this);
        };

        return _Class;

      })(),
      saveAll: function(tagList, fn) {
        var q;
        q = {};
        q[R.key.persistence_tag] = JSON.stringify(tagList);
        return chrome.storage.sync.set(q, fn);
      },
      loadAll: function(fn) {
        return chrome.storage.sync.get(R.key.persistence_tag, function(obj) {
          var tagList;
          if (obj[R.key.category] === void 0) {
            return;
          }
          tagList = JSON.parse(obj[R.key.category]);
          return typeof fn === "function" ? fn(tagList) : void 0;
        });
      }
    };
  });

}).call(this);
