// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', 'EventEmitter'], function(R, EE) {
    var port;
    port = null;
    return {
      send: function() {
        return port.postMessage.apply(port, arguments);
      },
      init: function() {
        return $(document).ready(function() {
          port = chrome.runtime.connect();
          return port.onMessage.addListener(function(req) {
            console.log(req);
            switch (req.type) {
              case R.key.resume_timer:
                return EE.trigger(R.key.resume_timer, req);
              case R.key.update_timer:
                return EE.trigger(R.key.update_timer, req);
              case R.key.end_timer:
                return EE.trigger(R.key.end_timer, req);
            }
          });
        });
      }
    };
  });

}).call(this);
