// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var $clock, normalize, toString, _separator_;
    _separator_ = ':';
    $clock = null;
    $(document).ready(function() {
      return $clock = $('.clock');
    });
    normalize = function(n) {
      if (n < 10) {
        return '0'.concat(n);
      } else {
        return '' + n;
      }
    };
    toString = function(secs) {
      var h, m, s;
      h = Math.floor(((secs % 31536000) % 86400) / 3600);
      m = Math.floor((((secs % 31536000) % 86400) % 3600) / 60);
      s = (((secs % 31536000) % 86400) % 3600) % 60;
      return (h > 0 ? normalize(h) + _separator_ : '') + (normalize(m) + _separator_) + normalize(s);
    };
    return {
      update: function(secs) {
        if (!!$clock) {
          return $clock.text(toString(secs));
        }
      }
    };
  });

}).call(this);
