// Generated by CoffeeScript 1.6.3
(function() {
  define(['R'], function(R) {
    var $clock, normalize, toString, tot_sec, _separator_;
    _separator_ = ':';
    $clock = null;
    tot_sec = R.int.default_time / 1000;
    $(document).ready(function() {
      return $clock = $('.clock');
    });
    normalize = function(n) {
      if (n < 10) {
        return '0'.concat(n);
      } else {
        return '' + n;
      }
    };
    toString = function(secs) {
      var h, m, s;
      h = Math.floor(((secs % 31536000) % 86400) / 3600);
      m = Math.floor((((secs % 31536000) % 86400) % 3600) / 60);
      s = (((secs % 31536000) % 86400) % 3600) % 60;
      return (h > 0 ? normalize(h) + _separator_ : '') + (normalize(m) + _separator_) + normalize(s);
    };
    return {
      update: function(secs) {
        if (!!$clock) {
          return $clock.text(toString(tot_sec - secs));
        }
      },
      reset: function() {
        if (!!$clock) {
          return $clock.text(toString(tot_sec));
        }
      }
    };
  });

}).call(this);
