// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', 'EventEmitter', 'ConnectionManager', 'Clock'], function(R, EE, CM, Clock) {
    var $playBtn, $stopBtn, fnPlayPause, fnStop, _pause, _play, _stop;
    $playBtn = $stopBtn = null;
    _play = function() {
      return $playBtn.removeClass('play').addClass('pause').children().removeClass('uk-icon-play').addClass('uk-icon-pause');
    };
    _pause = function() {
      return $playBtn.removeClass('pause').addClass('play').children().removeClass('uk-icon-pause').addClass('uk-icon-play');
    };
    _stop = function() {
      if ($playBtn.hasClass('pause')) {
        _pause();
      }
      return Clock.reset();
    };
    fnPlayPause = function() {
      if ($playBtn.hasClass('play')) {
        CM.send({
          "type": R.key.start_timer,
          "time": R.int.default_time
        });
        return _play();
      } else if ($playBtn.hasClass('pause')) {
        CM.send({
          "type": R.key.pause_timer
        });
        return _pause();
      }
    };
    fnStop = function() {
      CM.send({
        "type": R.key.stop_timer
      });
      return _stop();
    };
    return $(document).ready(function() {
      console.log('init player');
      $playBtn = $('.play').click(fnPlayPause);
      $stopBtn = $('.stop').click(fnStop);
      EE.on(R.key.resume_timer, function(req) {
        Clock.update(req.secs);
        return _play();
      });
      EE.on(R.key.update_clock, function(req) {
        return Clock.update(req.secs);
      });
      return EE.on(R.key.end_timer, function(req) {
        return _stop();
      });
    });
  });

}).call(this);
