// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', 'MessageEmitter'], function(R, MessageEmitter) {
    var fnPlayPause, fnStop;
    fnPlayPause = function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('play')) {
        MessageEmitter.start();
        return $this.removeClass('play').addClass('pause');
      } else if ($this.hasClass('pause')) {
        MessageEmitter.pause();
        return $this.removeClass('pause').addClass('play');
      }
    };
    fnStop = function() {
      return MessageEmitter.stop();
    };
    return $(document).ready(function() {
      var $playBtn, $stopBtn;
      console.log('init player');
      $playBtn = $('.play').click(fnPlayPause);
      return $stopBtn = $('.stop').click(fnStop);
    });
  });

}).call(this);
