// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', '_', 'TagIO', 'EventEmitter'], function(R, _, TagIO, EE) {
    var $tag, $tagList, $tagListHeader, createTableRow, _target;
    _target = null;
    $tag = $tagList = $tagListHeader = null;
    createTableRow = function(tag, tomatoes) {
      var $del, $tagRow;
      $tagRow = $("<tr><td>" + tag + "</td><td>" + tomatoes + "</td></tr>");
      $tagRow.find('td').addClass('clickable').click(function() {
        $tag.val(tag);
        return $tagListHeader.click();
      });
      $del = $('<i class="tag-del uk-icon-remove-sign"></i>').click(function() {
        $(this).parent().parent().remove();
        TagIO.remove(tag);
        console.log($tagList.children().size());
        if ($tagList.children().size() === 0) {
          return $tagListHeader.addClass('hidden');
        }
      });
      $tagRow.append($('<td class="tag-del-container">').append($del));
      return $tagList.append($tagRow);
    };
    return {
      disable: function() {
        return $tag.attr('disabled', '');
      },
      enable: function() {
        return $tag.removeAttr('disabled');
      },
      isDisabled: function() {
        return $tag.attr('disabled') != null;
      },
      getValue: function() {
        return $tag.val();
      },
      switchList: function() {
        if ($tagList.children().length > 0) {
          return $tagList.children().remove();
        } else {
          $tagList.addClass('uk-animation-slide-left').addClass('hidden');
          return TagIO.loadAll(function(tagMap) {
            var tag, tomatoes;
            for (tag in tagMap) {
              tomatoes = tagMap[tag];
              createTableRow(tag, tomatoes);
            }
            return $tagList.removeClass('hidden');
          });
        }
      },
      init: function() {
        var that;
        that = this;
        return $(document).ready(function() {
          $tag = $('.current-tag');
          $tagListHeader = $('.tags-btn');
          TagIO.loadAll(function(tagMap) {
            if (_.getSize(tagMap) > 0) {
              return $tagListHeader.removeClass('hidden');
            }
          });
          $tagList = $('.tags').find('tbody');
          $tagListHeader.click(function() {
            return that.switchList();
          });
          EE.on(R.key.play_clock, function() {
            that.disable();
            return TagIO.saveCurrent($tag.val());
          });
          EE.on(R.key.stop_clock, function() {
            that.enable();
            return $tag.val('');
          });
          EE.on(R.key.end_timer, function() {
            that.enable();
            return $tag.val('');
          });
          return EE.on(R.key.resume_timer, function() {
            that.disable();
            return TagIO.loadCurrent(function(tag) {
              return $tag.val(tag);
            });
          });
        });
      }
    };
  });

}).call(this);
