// Generated by CoffeeScript 1.6.3
(function() {
  define(['TagIO'], function(TagIO) {
    var $tag, disable, enable, _target;
    _target = null;
    $tag = null;
    disable = function() {
      return $tag.attr('disabled', '');
    };
    enable = function() {
      return $tag.removeAttr('disabled');
    };
    return $(document).ready(function() {
      return $tag = $('.current-tag');
    });
  });

}).call(this);
