// Generated by CoffeeScript 1.6.3
(function() {
  define(['R'], function(R) {
    return {
      start: function(cb) {
        return chrome.runtime.sendMessage({
          "type": R.string.start_timer,
          "time": R.int.default_time
        }, function(res) {
          return typeof cb === "function" ? cb(cb(res)) : void 0;
        });
      },
      pause: function(cb) {
        return chrome.runtime.sendMessage({
          "type": R.string.pause_timer
        }, function(res) {
          return typeof cb === "function" ? cb(cb(res)) : void 0;
        });
      },
      stop: function(cb) {
        return chrome.runtime.sendMessage({
          "type": R.string.stop_timer
        }, function(res) {
          return typeof cb === "function" ? cb(cb(res)) : void 0;
        });
      },
      bind: function(cb) {
        var port;
        port = chrome.runtime.connect();
        return port.onMessage.addListener(function(msg) {
          return cb(msg);
        });
      }
    };
  });

}).call(this);
